backend:
  name: github
  repo: pete22b/elite-escapes
  branch: main

media_folder: "img"
public_folder: "img"

collections:
  - name: "home"
    label: "หน้าแรก"
    files:
      - file: "_data/home.json"
        label: "หน้าแรก (Home)"
        name: "home"
        fields:
          - {label: "รูป Hero", name: "hero_image", widget: "image"}
          - {label: "หัวข้อ", name: "hero_title", widget: "string"}
          - {label: "คำโปรย", name: "hero_subtitle", widget: "text"}
          - {label: "เบอร์โทร", name: "phone", widget: "string"}
          - {label: "อีเมล", name: "email", widget: "string"}
